name: imagick
adopt-info: imagick
summary: Imagick is a PHP extension to create and modify images
description: |
  Imagick is a PHP extension to create and modify images using the ImageMagick library. 
  There is also a version of Imagick available for HHVM. Although the two extensions are mostly
  compatible in their API, and they both call the ImageMagick library, the two extensions are
  completely separate code-bases.

license: PHP-3.01

base: core20
grade: stable
confinement: strict
compression: lzo

parts:
  imagick:
    source: https://github.com/Imagick/imagick
    source-type: git
    plugin: nil
    override-build: | 
      git clone https://github.com/Imagick/imagick
      cd imagick
      phpize && ./configure
      make
      make install

    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"

    build-packages:
      - php-all-dev
      - pkg-config
      - libmagickwand-dev
      
    stage:
      - modules/
